// Reverb: three rooms out of one builder, every one of them generated.
//
//   input -> predelay -> lowcut -> damp -> convolver -> level -> wet
//
// The record has three fixed convolution sends already (`master.ts`: a hall, a
// short bright room for the clap, a long one for the piano), each with its
// impulse generated by `dsp.ts`'s own `impulseResponse`. Those are untouched.
// This is the same idea as an **instance**: the room is a parameter, so a
// strategy can put a plate on a stab and a hall behind a pad without a second
// graph being written, and the shapes live in `effects/spaces.ts` where what
// makes a plate a plate is four numbers and not a name.
//
// Three decisions in the chain and each is a measurement somebody else already
// made:
//
//   **The low cut is in front of the convolver, not behind it.** A reverb fed
//   the bottom two octaves puts a second bass in the record a beat late, and
//   taking it out afterwards takes out the low end of the tail as well as the
//   low end of the send. `master.ts` cuts its own reverb send at 220 Hz for
//   exactly this reason and carries the note.
//
//   **The damping is a filter on the way in and a tilt inside the impulse.**
//   A lowpass on the output darkens the *head* of the tail as much as the end
//   of it, and a room does not do that: what a room does is absorb more of the
//   top the longer a sound has been bouncing. So the tilt is baked into the
//   impulse (`spaces.ts`) and `dampHz` is the lid on what goes in.
//
//   **`decaySeconds` resamples the shape rather than cutting it.** Each room is
//   a unit-length shape and the buffer is rendered at the length asked for, so
//   a two-second hall and a six-second hall are the same room at two sizes and
//   not one room truncated.
//
// It is the one `dear` effect in the kitchen and it is dear for a reason a node
// count does not show: a convolution is the sample rate times the tail in
// multiplies a second, and the buffer behind it is two channels of `decay`
// seconds that have to be generated before the first sample is computed. Both
// are cached per context and per shape, which is what makes a rota affordable.

import { shell, knob } from './shell.ts';
import { room, ROOMS } from './spaces.ts';
import { resolveParams, guardParams } from './contract.ts';
import type { EffectDescriptor, EffectInstance, EffectParams } from './contract.ts';
import type { Settings } from '../settings.ts';

/** The declared tail, in one place: the builder and the descriptor read it. */
const TAIL = 8.3;

/**
 * @param settings the room it is built in; this one reads nothing from it
 */
export function build(ctx: BaseAudioContext, settings: Settings, params: EffectParams = {}): EffectInstance {
  const p = resolveParams(descriptor, params);
  const sh = shell(ctx, { mix: p.mix, tail: TAIL });

  const pre = ctx.createDelay(0.25);
  pre.delayTime.value = p.predelayMs / 1000;
  const cut = ctx.createBiquadFilter();
  cut.type = 'highpass';
  // Decibels of resonance at the corner and not a linear Q, which is the trap
  // `master.ts` and round K1 both carry a note about. Butterworth is -3.01.
  cut.Q.value = -3.01;
  cut.frequency.value = p.lowCutHz;
  const damp = ctx.createBiquadFilter();
  damp.type = 'lowpass';
  damp.Q.value = -3.01;
  damp.frequency.value = p.dampHz;
  const conv = ctx.createConvolver();
  const level = ctx.createGain();
  level.gain.value = p.level;

  let mode = Math.round(p.mode);
  let seconds = p.decaySeconds;
  const shape = (): void => {
    const r = ROOMS[Math.max(0, Math.min(ROOMS.length - 1, mode))];
    conv.buffer = room(ctx, { ...r, seconds: Math.max(0.1, seconds) });
  };
  shape();

  sh.input.connect(pre);
  pre.connect(cut);
  cut.connect(damp);
  damp.connect(conv);
  conv.connect(level);
  level.connect(sh.wet);
  sh.nodes.push(pre, cut, damp, conv, level);

  const preKnob = knob(ctx, pre.delayTime, p.predelayMs / 1000);

  return {
    input: sh.input,
    output: sh.output,
    params: guardParams(descriptor, {
      // A room and a size are both the buffer, so both are setters that swap
      // it: the shapes are cached per context, so asking for one that has been
      // asked for before costs a map lookup and nothing else. It is a `k`
      // parameter and the descriptor says so — a convolver's buffer cannot be
      // crossfaded from inside one node, and a strategy that wants to move
      // between two rooms builds two instances and crossfades them, which is
      // what a desk with two reverbs on it is.
      mode: (v) => { mode = Math.round(v); shape(); },
      decaySeconds: (v) => { seconds = Math.max(0.1, v); shape(); },
      predelayMs: (v, at, over) => preKnob(v / 1000, at, over),
      lowCutHz: cut.frequency,
      dampHz: damp.frequency,
      level: level.gain,
      mix: sh.setMix,
    }),
    setBypass: sh.setBypass,
    dispose: sh.dispose,
  };
}

export const descriptor: EffectDescriptor = {
  id: 'reverb',
  family: 'time',
  scope: 'send',
  // A send, so what it applies to is buses — and all five of them, because
  // there is no bus in this record a room is wrong for; how *much* of one is a
  // mix and a strategy's business.
  applies: ['kick', 'sub', 'drums', 'melodic', 'keys'],
  params: {
    // 0 room, 1 hall, 2 plate. The order is `spaces.ts`'s ROOMS and the
    // descriptor is where it is written down.
    mode: { unit: 'index', min: 0, max: 2, default: 1, rate: 'k' },
    decaySeconds: { unit: 'seconds', min: 0.2, max: 8, default: 2.2, rate: 'k' },
    predelayMs: { unit: 'ms', min: 0, max: 200, default: 0, rate: 'k' },
    lowCutHz: { unit: 'hz', min: 20, max: 1200, default: 220, rate: 'a' },
    dampHz: { unit: 'hz', min: 800, max: 18000, default: 6500, rate: 'a' },
    level: { unit: 'ratio', min: 0, max: 2, default: 1, rate: 'a' },
    mix: { unit: 'ratio', min: 0, max: 1, default: 0.3, rate: 'k' },
  },
  cost: 'dear',
  bypass: 'reverb',
  // The bound over the range and not the reading at the defaults: the longest
  // tail the parameters allow plus the deepest predelay. At the defaults it is
  // 2.2 s.
  tail: { seconds: TAIL },
  // The impulse's first sample is its loudest, so the wet path is not late
  // against its own input — until a predelay is asked for, which is the caller
  // asking for it and is why the default is nought.
  latency: 'none',
  build,
};

export default build;
